project:
  type: website
  output-dir: docs

website:
  title: "Habtamu Bizuayehu"  # Displayed next to the logo
  navbar:
    logo: top_logo.jpg  # Logo image in navbar
    left:
      - text: "Home"
        file: index.qmd
      - text: "About Me"
        file: about.qmd
      - text: "Skills and Expertise"
        file: Skillsets.qmd
      - text: "Resume/CV"
        file: CV.qmd
      - text: "Publication & Reports"
        file: Publication_report.qmd
      - text: "Projects & Blog"
        file: Podcast_Blog.qmd
    
    right:
      - icon: envelope
        text: "Contact Me"
        file: contact.qmd
      - icon: github
        # text: GitHub
        href: https://github.com/HabtamuBizuayehu?tab=repositories
        target: _blank
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/dr-habtamu-mellie-bizuayehu-94285980/
        target: _blank
      - icon: mortarboard-fill
        # text: Google Scholar
        href: https://scholar.google.com.au/citations?hl=en&user=zHEXO-IAAAAJ
        target: _blank
      - icon: orcid
        text: ORCID
        href: https://orcid.org/0000-0002-1360-4909
        target: _blank
      - icon: youtube
        text: YouTube
        href: https://www.youtube.com/channel/UCLVKP0g8GvHhOh0kn20T8eg
        target: _blank

# 
#  right:
#       - text: "Contact"
#         file: contact.qmd
#       - icon: github
#         text: GitHub
#         href: https://github.com/
#         target: _blank
#       - icon: twitter
#         text: Twitter
#         href: https://twitter.com
#         target: _blank
#       - icon: linkedin
#         text: LinkedIn
#         href: https://www.linkedin.com/in/dr-habtamu-mellie-bizuayehu-94285980/
#         target: _blank
#       - icon: envelope
#         text: Email
#         href: mailto:hmba2003@gmail.com
#         target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true  # Optional: Table of contents on the side
    toc-depth: 2

editor: visual
